- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt




name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code with Ruff
      run: |
        ruff src tests

    - name: Type check with mypy
      run: |
        mypy src tests

    - name: Run unit tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        coverage run -m unittest discover -s tests -v
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        fail_ci_if_error: true
